name: CI-Linux

on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:  
  build-linux:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: build
        run: dotnet build
      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: linux-build-result
          path: .

  test-linux:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - name: download build
        uses: actions/download-artifact@v2
        with:
          name: linux-build-result
      - name: test
        run: 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\TestResults\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov'
      - name: publish results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: 'Unit Tests Results for Linux'
          files: ./TestResults/*test-result.xml
      - name: Publish coverage report for Arnible.Test
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./Arnible.Test/TestResults/coverage.info
      - name: Publish coverage report for Arnible.Export.Test
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./Arnible.Export.Test/TestResults/coverage.info
      - name: Publish coverage report for Arnible.Linq.Test
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./Arnible.Linq.Test/TestResults/coverage.info
      - name: Publish coverage report for Arnible.MathModeling.Test
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./Arnible.MathModeling.Test/TestResults/coverage.info
      - name: Publish coverage report for Arnible.MathModeling.Formal.Test
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./Arnible.MathModeling.Formal.Test/TestResults/coverage.info
